name: dbt_run_scheduled_confirm_blocks_temp
run-name: dbt_run_scheduled_confirm_blocks_temp

on:
  workflow_dispatch:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@pre-release/v4-beta
    with:
      warehouse: DBT_EMERGENCY
      command_name: Run Main Models
      command: |
        dbt run -m "fsc_evm,tag:silver,tag:confirm_blocks"
    secrets: inherit