name: dbt_run_overflowed_traces
run-name: dbt_run_overflowed_traces

on:
  workflow_dispatch:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@pre-release/v4-beta
    with:
      command_name: Run Overflow Models
      command: |
        dbt run -m "fsc_evm,tag:overflowed_traces" --vars '{"OVERFLOWED_TRACES":True}'
    secrets: inherit