version: 2

sources:
  - name: ethereum
    database: ethereum
    schema: core
    tables:
      - name: fact_hourly_token_prices
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "BASE_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "BASE" }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: debug_traceBlockByNumber
      - name: decoded_logs
      - name: confirm_blocks
      - name: goerli_blocks
      - name: goerli_transactions
      - name: goerli_debug_traceTransaction
      - name: goerli_eth_getTransactionReceipt
  - name: udfs_streamline
    database: udfs
    schema: streamline
    tables:
      - name: node_mapping
  - name: silver_crosschain
    database: crosschain
    schema: silver
    tables:
      - name: number_sequence
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: base_state_hashes
