version: 2

sources:
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "BASE_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "BASE" }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: debug_traceblockbynumber
      - name: decoded_logs
      - name: confirm_blocks
      - name: blocks_v2
      - name: transactions_v2
      - name: receipts_v2
      - name: traces_v2
      - name: confirm_blocks_v2
      - name: decoded_logs_v2
      - name: contract_abis
  - name: crosschain
    database: >-
      {{ 'CROSSCHAIN_DEV' if '_DEV' in target.database.upper() else 'CROSSCHAIN' }}
    schema: core
    tables:
      - name: dim_labels
  - name: crosschain_silver
    database: >-
      {{ 'CROSSCHAIN_DEV' if '_DEV' in target.database.upper() else 'CROSSCHAIN' }}
    schema: silver
    tables:
      - name: near_address_encoded
      - name: labels_combined
      - name: complete_provider_asset_metadata
      - name: complete_native_asset_metadata
      - name: complete_native_prices
      - name: complete_provider_prices
      - name: complete_token_asset_metadata
      - name: complete_token_prices
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: base_state_hashes
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: complete_streamline
    database: "{{ target.database }}"
    schema: streamline
    tables:
      - name: complete_contract_abis
  - name: base_bronze_api
    database: base
    schema: bronze_api
    tables:
      - name: contract_abis
  - name: github_actions
    database: "{{ target.database }}"
    schema: github_actions
    tables:
      - name: workflows
  - name: external_gold_defillama
    database: external
    schema: defillama
    tables:
      - name: dim_chains
  - name: base_silver
    database: "{{ 'base' if target.database == 'BASE' else 'base_dev' }}"
    schema: silver
    tables:
      - name: overflowed_traces
  - name: base_gold
    database: "{{ 'base' if target.database == 'BASE' else 'base_dev' }}"
    schema: core
    tables:
      - name: fact_traces
  - name: abis_silver
    database: "{{ target.database }}"
    schema: silver
    tables:
      - name: verified_abis
  - name: fsc_evm_admin
    database: >-
      {{ 'FSC_EVM_DEV' if '_DEV' in target.database.upper() else 'FSC_EVM' }}
    schema: admin
    tables:
      - name: _master_keys
      - name: rpc_node_logs
  - name: logs_temp
    database: "{{ target.database }}"
    schema: silver
    tables:
      - name: logs
