version: 2

sources:
  - name: ethereum
    database: ethereum
    schema: core
    tables:
      - name: fact_hourly_token_prices
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "BASE_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "BASE" }}
    tables:
      - name: blocks
      - name: transactions
      - name: debug_traceTransaction
      - name: eth_getTransactionReceipt
  - name: udfs_streamline
    database: udfs
    schema: streamline
    tables:
      - name: node_mapping
