version: 2

sources:
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ var('GLOBAL_PROD_DB_NAME') ~ ('_dev' if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else '') }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: debug_traceblockbynumber
      - name: decoded_logs
      - name: confirm_blocks
      - name: goerli_blocks
      - name: goerli_transactions
      - name: goerli_debug_traceTransaction
      - name: goerli_eth_getTransactionReceipt
      - name: blocks_v2
      - name: transactions_v2
      - name: receipts_v2
      - name: traces_v2
      - name: confirm_blocks_v2
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'BASE' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_labels
  - name: silver_crosschain
    database: "{{ 'crosschain' if target.database == 'BASE' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: near_address_encoded
      - name: labels_combined
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: base_state_hashes
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: streamline_crosschain
    database: streamline
    schema: crosschain
    tables:
      - name: node_mapping
  - name: base_silver
    database: base
    schema: silver
    tables:
      - name: verified_abis
  - name: base_bronze_api
    database: base
    schema: bronze_api
    tables:
      - name: contract_abis
  - name: github_actions
    database: base
    schema: github_actions
    tables:
      - name: workflows
  - name: external_gold_defillama
    database: external
    schema: defillama
    tables:
      - name: dim_chains
  - name: base_silver
    database: "{{ 'base' if target.database == 'BASE' else 'base_dev' }}"
    schema: silver
    tables:
      - name: overflowed_traces2